<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function bootstrap_barrio_subtheme_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
  $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function bootstrap_barrio_subtheme_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  // Detectar si estamos en un formulario de creación o edición de entidad (nodo u otros tipos).
  $is_form = FALSE;
  
  if (isset($route_name)) {
    // Patrones comunes para formularios en Drupal, rutas de usuario, vistas y nodos
    $user_routes = ['user.login', 'user.register', 'user.pass', 'user.reset'];
    if (strpos($route_name, '.add') !== FALSE || strpos($route_name, '.edit') !== FALSE || strpos($route_name, '_form') !== FALSE || strpos($route_name, 'view.') !== FALSE || $route_name == 'entity.node.canonical' || $route_name == 'node.add' || in_array($route_name, $user_routes)) {
      $is_form = TRUE;
    }
  }

  $variables['is_entity_form'] = $is_form;
}
