<?php

declare(strict_types=1);

/**
 * @file
 * Provides a Evaluación de retos entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function zinco_retos_evaluacion_theme(): array {
  return [
    'zinco_retos_evaluacion' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for Evaluación de retos templates.
 *
 * Default template: zinco-retos-evaluacion.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the Evaluación de retos information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zinco_retos_evaluacion(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function zinco_retos_evaluacion_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish Evaluaciones de retos.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_retos_evaluacion');
      $zinco_retos_evaluacion_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_retos_evaluacion_ids) as $zinco_retos_evaluacion) {
        $zinco_retos_evaluacion->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize Evaluaciones de retos.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_retos_evaluacion');
      $zinco_retos_evaluacion_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_retos_evaluacion_ids) as $zinco_retos_evaluacion) {
        $zinco_retos_evaluacion->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function zinco_retos_evaluacion_user_predelete(UserInterface $account): void {
  // Delete Evaluaciones de retos that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('zinco_retos_evaluacion');
  $zinco_retos_evaluacion_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($zinco_retos_evaluacion_ids)
  );
}
