<?php

declare(strict_types=1);

/**
 * @file
 * Provides a zinco reconocimientos entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function zinco_reconocimientos_theme(): array {
  return [
    'zinco_reconocimientos' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for zinco reconocimientos templates.
 *
 * Default template: zinco-reconocimientos.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the zinco reconocimientos information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zinco_reconocimientos(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function zinco_reconocimientos_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish zinco reconocimientoss.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_reconocimientos');
      $zinco_reconocimientos_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_reconocimientos_ids) as $zinco_reconocimientos) {
        $zinco_reconocimientos->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize zinco reconocimientoss.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_reconocimientos');
      $zinco_reconocimientos_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_reconocimientos_ids) as $zinco_reconocimientos) {
        $zinco_reconocimientos->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function zinco_reconocimientos_user_predelete(UserInterface $account): void {
  // Delete zinco reconocimientoss that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('zinco_reconocimientos');
  $zinco_reconocimientos_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($zinco_reconocimientos_ids)
  );
}
