zinco_ctei_actores.actores.*:
  type: config_entity
  label: Actores
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

zinco_ctei_actores.actors.*:
  type: config_entity
  label: Actors
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

zinco_ctei_actores.cteiactor.*:
  type: config_entity
  label: CTEIActor
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
