<?php

/**
 * @file
 * Primary hook implementations for the Zinco Front module.
 */
use Drupal\user\UserInterface;
/**
 * Implements hook_theme().
 */
function zinco_front_theme($existing_theme, $type, $theme_name) {
  return [
    'zinco_front_user_menu' => [
      'variables' => [
        'logged_in' => FALSE,
        'user_name' => '',
        'user_picture' => NULL,
        'unread_notifications' => 0,
        'logout_url' => '',
      ],
      'template' => 'block--user-menu',
    ],
  ];
}

/**
 * Implements hook_user_update().
 */
function zinco_front_user_update(UserInterface $account) {
  // Invalidate the user data cache when a user is updated.
  var_dump($account->getCacheTags());
  \Drupal::service('cache_tags.invalidator')->invalidateTags($account->getCacheTags());
}

