<?php

declare(strict_types=1);

/**
 * @file
 * Provides a zincoactor entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function zinco_ctei_actores_theme(): array {
  return [
    'zincoactor' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for zincoactor templates.
 *
 * Default template: zincoactor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the zincoactor information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zincoactor(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function zinco_ctei_actores_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish zincoactors.
      $storage = \Drupal::entityTypeManager()->getStorage('zincoactor');
      $zincoactor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zincoactor_ids) as $zincoactor) {
        $zincoactor->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize zincoactors.
      $storage = \Drupal::entityTypeManager()->getStorage('zincoactor');
      $zincoactor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zincoactor_ids) as $zincoactor) {
        $zincoactor->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function zinco_ctei_actores_user_predelete(UserInterface $account): void {
  // Delete zincoactors that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('zincoactor');
  $zincoactor_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($zincoactor_ids)
  );
}

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function zinco_ctei_actores_theme(): array {
  return [
    'cteiactor' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for cteiactor templates.
 *
 * Default template: cteiactor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the cteiactor information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_cteiactor(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function zinco_ctei_actores_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish cteiactors.
      $storage = \Drupal::entityTypeManager()->getStorage('cteiactor');
      $cteiactor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($cteiactor_ids) as $cteiactor) {
        $cteiactor->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize cteiactors.
      $storage = \Drupal::entityTypeManager()->getStorage('cteiactor');
      $cteiactor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($cteiactor_ids) as $cteiactor) {
        $cteiactor->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function zinco_ctei_actores_user_predelete(UserInterface $account): void {
  // Delete cteiactors that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('cteiactor');
  $cteiactor_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($cteiactor_ids)
  );
}
