<?php

declare(strict_types=1);

/**
 * @file
 * Provides a zinco grupos investigacion entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function zinco_grupos_investigacion_theme(): array {
  return [
    'zinco_grupos_investigacion' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for zinco grupos investigacion templates.
 *
 * Default template: zinco-grupos-investigacion.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the zinco grupos investigacion information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_zinco_grupos_investigacion(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function zinco_grupos_investigacion_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish zinco grupos investigacions.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_grupos_investigacion');
      $zinco_grupos_investigacion_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_grupos_investigacion_ids) as $zinco_grupos_investigacion) {
        $zinco_grupos_investigacion->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize zinco grupos investigacions.
      $storage = \Drupal::entityTypeManager()->getStorage('zinco_grupos_investigacion');
      $zinco_grupos_investigacion_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($zinco_grupos_investigacion_ids) as $zinco_grupos_investigacion) {
        $zinco_grupos_investigacion->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function zinco_grupos_investigacion_user_predelete(UserInterface $account): void {
  // Delete zinco grupos investigacions that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('zinco_grupos_investigacion');
  $zinco_grupos_investigacion_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($zinco_grupos_investigacion_ids)
  );
}
